version: '1.0'
services:
  zookeeper:
    image: zookeeper:3.4.13
    container_name: zookeeper
    restart: always
    networks:
      - api-gateway
    ports:
      - "2181:2181"

networks:
  api-gateway:
    driver: bridge